# Generated by Django 4.2 on 2024-11-15 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lob_id', models.CharField(max_length=50)),
                ('site_visit', models.CharField(max_length=100)),
                ('quotation', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('pending_amount', models.FloatField()),
                ('status', models.CharField(max_length=50)),
                ('po', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('payment_status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.user')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
